### ISSUE TITLE
APRS.fi API Key In Code

### ISSUE THREAD

**Issue by LRenegar** [UMDBPP/public_site#1]
The APRS.fi API key is publicly in the code. This lets people steal the API key. See https://softwareengineering.stackexchange.com/questions/205606/strategy-for-keeping-secret-info-such-as-api-keys-out-of-source-control for suggestions on how to deal with this. TL;DR is to find a way to put it in a config file that doesn't live in source control. A template, such as project.config.default lives in source control, but the project.config file itself is .gitignore'd to prevent secrets from accidentally leaking. After this is fixed, you'll need to regenerate the key, as it's already been compromised.

**Comment by zacharyburnett** [comment]
Truly fixing this problem will require server-side API calls, which are probably the better solution anyway. Otherwise, the API key will be visible to the user anyway in the client.

**Comment by LRenegar** [comment]
As mentioned in issue #2 , we need to migrate this server-side, which would indeed fix the problem. In the interim, though, it's still not great practice to expose things like this on GitHub. If people want to go to the trouble of scraping your webpage to find the keys, so be it, but putting it on GitHub increases your attack surface fairly dramatically. It also makes it trivially easy for someone else to stand up a copy of the website and steal your API quota without even realizing what they've done.

**Comment by zacharyburnett** [comment]
Alright, I'll make the key gitignored then.

**Comment by zacharyburnett** [comment]
fixed in [7df1794bd42b072a14d78c35d83a002defb2e553](https://github.com/UMDBPP/public_site/commit/7df1794bd42b072a14d78c35d83a002defb2e553)
